name: Deploy Infra

on:
  workflow_dispatch:

env:
  storageNamePrefix: labtest
  resourceGroupName: lab

jobs:
  infra-deploy:
  runs-on: ubuntu-latest
  steps:
   - name: Checkout
     uses: actions/checkout@v4

   # login into Azure
   - name: Azure login
     uses: azure/login@v2
     with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

   # Deploy the bicep template
   - name: Deploy Azure Resource Manager (ARM) Template
     uses: azure/arm-deploy@v2
     with: 
        subscriptionId: ${{ secrets.AZURE_SUBSCRIPTION}}
        resourceGroupName: ${{ env.resourceGroupName }}
        template: ./infra/templates/deploy_envt.bicep
        parameters: ./infra/evnts/production/deploy_evnt.parameters.json storageNamePrefix=${{env.storageNamePrefix}}
      
     