name: A Basic Workflow
on:
  push:
    branches: 
        - main
  
  pull_request: 
    branches: 
        - main
        
  workflow_dispatch: 

env:
  GLOBAL_VAR: "This is global variable"  

jobs:
    build-app:
        env:
          JOB_VAR: "This is job variable"
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3
            - name: Run a one-line script
              run: | 
                echo Hello, world!
                echo $GLOBAL_VAR
                echo $JOB_VAR
                echo $STEP_VAR
              env:
               STEP_VAR: "This is step variable"

            - name: Run a multi-line script
              run: |
                echo Add other actions to build,
                echo test, and deploy your project.
                echo $STEP_VAR
            
            - name: Print Default Variables
              run: |
                echo "Runner OS: $RUNNER_OS"
                echo "Repository: $GITHUB_REPOSITORY"
                echo "Run Number: $GITHUB_RUN_NUMBER"

            - name: Checking artifacts
              run: echo Hello World from artifacts > "testing_artifacts.txt"

            - name : Upload artifacts
              uses : actions/upload-artifact@v4
              with:
                name: testing-artifact
                path: testing_artifacts.txt
                retention-days: 30
            
            - name: Download artifacts
              uses: actions/download-artifact@v4
              with:
                name: testing-artifact
                path: ./downloaded
            
            - name: Display artifact content
              run: cat ./downloaded/testing_artifacts.txt


    build-api:
        runs-on: windows-latest
        steps:
          - run: echo Building API ${{env.GLOBAL_VAR}}

    build-db:
        needs: build-app
        runs-on: windows-latest
        steps:
          - run: echo Hello Windows ${{env.GLOBAL_VAR}}


    packages: 
        needs: [build-app, build-db]
        runs-on: macos-latest
        steps:
          - run: echo Hello MacOS
    